"""added category and removed slug

Revision ID: 07e826111df5
Revises: 7ef9d87fb131
Create Date: 2022-10-28 12:13:58.823313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07e826111df5'
down_revision = '7ef9d87fb131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category', sa.String(length=255), nullable=False))
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('posts', 'category')
    # ### end Alembic commands ###
